### ISSUE TITLE
Change the resource extension of the verification resource from .kel/.oobi to .keri

### ISSUE THREAD

**Issue by 2byrds** [dhh1128/did-method-webs#35]
I think the spec would be better by referring to the did document file as did.json and the verification resource as did.keri

In last Friday's meeting we detailed several ways that a resolver reference impl could verify the did.json file.
In order to generically reference in the spec what the verification resource will contain, I suggest we use the .keri extension to refer to all of the keri KELs/TELs needed to verify the did document.

That's because did:webs could be retrieving resource from a web server like github and/or doing asynchronous oobi resolution and/or using watchers and/or a local db/cache to get the KELs/TELs necessary to verify the did document.

**Comment by swcurran** [comment]
I think that makes sense. Remove a bit of the lingo so it is a bit more obvious, and the definition in the spec can cover the subtleties as needed.
